name: Stock Alert Bot

on:
  schedule:
    - cron: "10 7 * * 1-5"
    - cron: "0 22 * * 1-5"
  workflow_dispatch:

jobs:
  run-stock-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: |
          pip install yfinance pandas requests numpy

      - name: Run stock alert bot
        run: |
          python stock_alert_bot.py
